# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DiwataBrowser
                                 A QGIS plugin
 This plugin enables user to browse and load Diwata-2 SMI products.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-08
        copyright            : (C) 2021 by STAMINA4Space
        email                : cnpante@stamina4space.upd.edu.ph
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DiwataBrowser class from file DiwataBrowser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .diwata_browser import DiwataBrowser
    return DiwataBrowser(iface)
